[project]
name = "srtmgl1-dem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cf-xarray>=0.10.5",
    "ipython>=9.3.0",
    "pydantic>=2.11.5",
    "requests>=2.32.3",
    "upath>=1.0",
]
