title: "SRTMGL1-DEM"
description: "Global 1-Arc Second Digital Elevation Model (DEM) derived from NASA's Shuttle Radar Topography Mission (SRTM). This dataset provides high-resolution topographic data for applications in hydrology, climate modeling, and terrain analysis."

recipes:
  - id: "SRTMGL1-DEM"
    object: "recipe:SRTMGL1-DEM"

provenance:
  providers:
    - name: "NASA Shuttle Radar Topography Mission (SRTM)"
      description: "NASA's SRTM mission collected high-resolution elevation data for nearly the entire Earth's land surface using radar interferometry."
      roles:
        - data provider
        - research institution
      url: "https://www2.jpl.nasa.gov/srtm/"

    - name: "Jet Propulsion Laboratory (JPL)"
      description: "JPL processes SRTM data for global digital elevation modeling, supporting geospatial analysis and environmental research."
      roles:
        - data provider
        - research institution
      url: "https://www.jpl.nasa.gov/"

  license: "Creative Commons Attribution 4.0 (CC BY 4.0)"

acknowledgements: >
  The SRTMGL1 Digital Elevation Model is based on data from NASA's Shuttle Radar Topography Mission (SRTM), which provided global elevation data with unprecedented accuracy. We acknowledge the **NASA SRTM mission team** and the **Jet Propulsion Laboratory (JPL)** for processing and maintaining this dataset. The dataset is widely used for geospatial applications, hydrological modeling, and terrain analysis.

citation:
  - authors: "Farr, T.G., Rosen, P.A., Caro, E., et al."
    year: 2007
    title: "The Shuttle Radar Topography Mission."
    journal: "Reviews of Geophysics"
    volume: 45
    pages: RG2004
    doi: "10.1029/2005RG000183"

contact:
  email: "srtm@nasa.gov"

maintainers:
  - name: "Mitra Cattry"
    github: "mitraA90"
  - name: "Raphael Hagen"
    github: "norlandrhagen"
